[workspace]
resolver = "2"
members = ["packages/*", "examples/*"]

[profile.dev]
# Debug info isn't useful most of the time. It slows down builds and uses up disk space.
# Disk space is particularly a problem for CI builds.
debug = 0

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"

[profile.bench]
opt-level = 3

[workspace.package]
# The version is used by all published crates however it is not updated for the
# internal silkenweb dependencies where it has to be updated manually.
version = "0.5.0"

# Defines the versions for all the workspace dependencies, including examples
# but does not specify features, which is done in each crate as needed
[workspace.dependencies]

# main dependencies
silkenweb = { path = "packages/silkenweb", version = "0.5.0" }
silkenweb-css = { path = "packages/css", version = "0.5.0" }
silkenweb-css-macros = { path = "packages/css-macros", version = "0.5.0" }
silkenweb-signals-ext = { path = "packages/signals-ext", version = "0.5.0" }
silkenweb-macros = { path = "packages/macros", version = "0.5.0" }
silkenweb-tauri-proc-macro = { path = "packages/tauri-proc-macro", version = "0.5.0" }
silkenweb-test = { path = "packages/test", version = "0.5.0" }

clonelet = "0.2.0"
js-sys = "0.3.60"
web-sys = "0.3.60"
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.33"
cssparser = "0.31.2"
lightningcss = "=1.0.0-alpha.44"
itertools = "0.11.0"
async-trait = "0.1.66"
axum = "0.6.10"
serde = "1.0.154"
serde_urlencoded = "0.7.1"
serde-wasm-bindgen = "0.5.0"
futures-signals = "0.3.31"
pin-project = "1.0.12"
paste = "1.0.9"
discard = "1.0.4"
futures = "0.3.24"
caseless = "0.2.1"
html-escape = "0.2.9"
indexmap = "2.0.0"
console_error_panic_hook = "0.1.7"
static_assertions = "1.1.0"
tokio = "1.25.0"
tokio-stream = "0.1.14"
gloo-timers = "0.2.6"

# macro dependencies
syn = "2.0.26"
proc-macro-error = "1.0.4"
quote = "1.0.15"
proc-macro2 = "1.0.36"
heck = "0.4.0"
derive_more = "0.99.17"
grass = "0.13.1"

# xtask dependencies
clap = "4.1.8"
xtask-base = { git = "https://github.com/simon-bourne/rust-xtask-base" }
xshell = "0.2.5"
duct = "0.13.5"
scopeguard = "1.1.0"

# Example dependencies
chrono = "0.4.19"
timeago = "0.4.1"
async-recursion = "1.0.0"
silkenweb-htmx-axum = { path = "packages/htmx-axum" }
web-log = "1.0.1"
rand = "0.8.5"
serde_json = "1.0.85"
parse-display = "0.8.0"
silkenweb-bootstrap = { path = "packages/bootstrap" }
silkenweb-bootstrap-macros = { path = "packages/bootstrap/macros" }
gloo-console = "0.2.3"
reqwasm = "0.5.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
num-traits = "0.2.15"
getrandom = "0.2.7"

arpy = { git = "https://github.com/simon-bourne/arpy" }
arpy-reqwasm = { git = "https://github.com/simon-bourne/arpy" }
arpy-server = { git = "https://github.com/simon-bourne/arpy" }
arpy-axum = { git = "https://github.com/simon-bourne/arpy" }

# test dependencies
wasm-bindgen-test = "0.3.28"
criterion = { version = "0.5.1", default-features = false }
trybuild = "1.0.76"
