[package]
name = "silkenweb-css"
version = { workspace = true }
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
description = "CSS crate for Silkenweb"
homepage = "https://github.com/silkenweb/silkenweb"
repository = "https://github.com/silkenweb/silkenweb"
license = "MIT OR Apache-2.0"

categories = ["gui", "web-programming"]
keywords = ["reactive", "web", "html", "browser", "dom"]

[dependencies]
cssparser = { workspace = true }
lightningcss = { workspace = true }
itertools = { workspace = true }
clonelet = { workspace = true }
