[package]
name = "silkenweb-style-macros"
version = { workspace = true }
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
description = "Macros for silkenweb-style"
homepage = "https://github.com/silkenweb/silkenweb"
repository = "https://github.com/silkenweb/silkenweb"
license = "MIT OR Apache-2.0"

categories = ["gui", "web-programming"]
keywords = ["reactive", "web", "html", "browser", "dom"]

[lib]
proc-macro = true

[dependencies]
silkenweb-style = { workspace = true }
lightningcss = { workspace = true }
proc-macro-error = { workspace = true }
proc-macro2 = { workspace = true }
syn = { workspace = true, features = ["full"] }
quote = { workspace = true }
grass = { workspace = true }
derive_more = { workspace = true }
